# Generated by Django 4.0.4 on 2022-05-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='username',
            field=models.CharField(default='GC', max_length=100),
            preserve_default=False,
        ),
    ]
