# Generated by Django 4.0.4 on 2022-05-18 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_person_username'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('first_name', 'last_name', 'username')},
        ),
    ]
