# Generated by Django 4.0.4 on 2022-05-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_topic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
