# Generated by Django 4.0.4 on 2022-05-27 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_message_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='body',
        ),
    ]
